name: Deploy Angular app to GitHub Pages

on:
  push:
    branches:
      - main  # or the default branch
    paths:
      - 'Health_ai/**'  # Only trigger on frontend changes

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd Health_ai
          npm ci
          
      - name: Build
        run: |
          cd Health_ai
          npm run build -- --configuration production --base-href=/Health-Ai/
          
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: Health_ai/dist/frontend  # Adjust this path if needed
          branch: gh-pages